### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by kcwashington** [litecoin-foundation/loafwallet-ios#100]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Observed Environment**
 - OS version [e.g. _iOS 13.0_]:
 - Litewallet Version [e.g. _v3.4.0_]:
 - Device model:[e.g. _iPhone 11_]:

**Additional context or information**

**Comment by korolossamy** [comment]
I notice the same after update os to 15.1
App force close before entering pin

**Comment by kcw-grunt** [comment]
Duplicate of #101
