### ISSUE TITLE
🦟[Bug Report]force close

### ISSUE THREAD

**Issue by korolossamy** [litecoin-foundation/loafwallet-ios#101]
**Describe the bug**
-application force close before entering pin , issue happened after updating ios 15.1

**To Reproduce**
1. Go to '...' open app
2. Click on '....' you not have chance for clicking, force close after 1-2 seconds 

**Screenshots**

**Observed Environment**
 - OS version [e.g. _iOS 13.0_]:iOS 15.1
 - Litewallet Version [e.g. _v3.4.0_]:3.6.1(3)
 - Device model:[e.g. _iPhone 11_]:Iphone 12 pro max

**Comment by Majidbaba** [comment]
Mining

**Comment by Majidbaba** [comment]
> Mining

**Comment by kcw-grunt** [comment]
thanks for this  @korolossamy .
We'll take a look.

**Comment by kcw-grunt** [comment]
Will you have them send a GIF , then write a new issue to the team repo, via LWDC @Patrick-t-mcdermott  ?

**Comment by kcw-grunt** [comment]
Resolved.
