### ISSUE TITLE
🦟[Bug Report]

### ISSUE THREAD

**Issue by Majidbaba** [litecoin-foundation/loafwallet-ios#104]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Observed Environment**
 - OS version [e.g. _iOS 13.0_]:
 - Litewallet Version [e.g. _v3.4.0_]:
 - Device model:[e.g. _iPhone 11_]:

**Additional context or information**

0x96E471B5945373dE238963B4E032D3574be4d195

**Comment by kcw-grunt** [comment]
Closing
