### ISSUE TITLE
Create new Wallet

### ISSUE THREAD

**Issue by bpran** [litecoin-foundation/loafwallet-ios#12]
if someone forget the pin and passphrase, they cannot create new wallet in the iOS device.
Even after they DELETE the app and REINSTALL the app again.

https://twitter.com/benyap168/status/967438728669970432

**Comment by kcw-grunt** [comment]
Yes..this is expected behavior.
The problem is on the one hand we provide complete transparency in the code base and notify the user the need to record/store their seed phrase.  This is common for all crypto wallets. Not just Loafwallet.
