### ISSUE TITLE
🦺[Tech Debt]  Apply unused script

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#122]
## Goal  

Use a Build Phase script to identify unused code in the code base

## Definition of Done
- [ ] Pick a method 2:  https://iosexample.com/a-tool-to-detect-unused-code/
- [ ] Pick a method 1: https://medium.com/@gabriel_lewis/how-to-easily-find-unused-swift-code-in-xcode-159631961acf
- [ ] Branch `develop/techdebt/XXXX-122`
- [ ] Submit a PR

**Comment by Iferencak** [comment]
Fixed in #145
