### ISSUE TITLE
Need submodule (litecoin-foundation/loafwallet-core) updates from breadwallet/breadwallet-core to

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#13]
+ 1000 Crashes are due to the submodule (loafwallet-core) not being updated.  breadwallet-core recent updates are declared 'API-Breaking' and are causing the crashes we see in LoafWallet

**Comment by kcw-grunt** [comment]
Hey @losh11 This is what we are slacking about.

**Comment by losh11** [comment]
Fixed in `4ddfe34`.
