### ISSUE TITLE
Force-unwrapping causes crash

### ISSUE THREAD

**Issue by nspassov** [litecoin-foundation/loafwallet-ios#139]
Dear loafwallet maintainers,

The following line of code causes a crash since iOS 14 on my device: `format.positiveFormat.range(of: "#")!`

The expression is used 5 times in this file:

https://github.com/litecoin-foundation/loafwallet-ios/blob/154eb4fbbe71b4ff1a2323dd316bf7b6783c3b0a/loafwallet/src/ViewModels/Amount.swift#L49

https://github.com/litecoin-foundation/loafwallet-ios/blob/154eb4fbbe71b4ff1a2323dd316bf7b6783c3b0a/loafwallet/src/ViewModels/Amount.swift#L63

https://github.com/litecoin-foundation/loafwallet-ios/blob/154eb4fbbe71b4ff1a2323dd316bf7b6783c3b0a/loafwallet/src/ViewModels/Amount.swift#L92

Obviously force-unwrapping is a bad practice, so this is no surprise. I am not really clear why this line of code is even needed, but it seems that with certain regional settings it causes a crash and loafwallet cannot be used.

I am willing to make a PR with fix for this but it would be useful if someone could clarify why this is even necessary (for now I have commented out this line just so I can access my wallet and not be locked out of my coins).

Best regards,
Nikolay

**Comment by kcw-grunt** [comment]
@nspassov thanks for uncovering a code smell. You are correct. 
This should never happen and it should be guarded at the very least, e.g;

https://github.com/litecoin-foundation/loafwallet-ios/blob/154eb4fbbe71b4ff1a2323dd316bf7b6783c3b0a/loafwallet/src/ModalPresenter.swift#L454
 
`guard let wm = self.walletManager else { print("NO WALLET MANAGER!"); return }`

or something similar.

Please feel free to open a PR and it will be looked at.

**Comment by nspassov** [comment]
Hi @kcw-grunt, it seems to me that the proper way to do it is actually very simple. Here is my PR:

https://github.com/litecoin-foundation/loafwallet-ios/pull/140

**Comment by kcw-grunt** [comment]
thanks for the help @nspassov
