### ISSUE TITLE
🦺[Tech Debt]  Remove Cruft: Retire HTTPS Server code

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#143]
## Goal 
**Describe the work to be done**
 
To better manage the codebase, we should remove old code that is not being used. In fact since the days of `Loafwallet`, this code was never used.  It makes adding features a bug fixing a nightmare.

In this case we should remove `BR  HTTPS Server code`.  Listed are some of the classes that are suspect:
  - BRHTTPFileMiddleware
  - BRHTTPFileMiddleware
  - BRHTTPIndexMiddleware
  - BRHTTPRouter
## Definition of Done
- [ ] Remove all related BRHTTPMiddleware
- [ ] Add basic tests (Maybe a binary size test as metric)

**Comment by Iferencak** [comment]
I removed all of the unused `BR HTTPS Sever code`, and related code. 

In a discussion with @kcw-grunt, we decided that for now we will track lines of code. That should give us a high level view of the size of the project, how the codebase is changing and potentially the complexity of that codebase.

On that topic, i found two solid options for achieving that goal:

**Option 1**
Simple terminal command
`find . -path ./Pods -prune -o -name '*.swift' -print0 ! -name '/Pods' | xargs -0 wc -l | grep "total"`
This is a nice and quick way to get the total count of all lines of code in all of the swift files (excluding pods).

**Option 2**
Using [cloc](https://github.com/AlDanial/cloc)
This is a great peace of code that can be installed with homebrew and gives much more detail.

Usage
`brew install cloc`
`cloc . --exclude-dir=Pods`

Output
![image](https://user-images.githubusercontent.com/19799406/200811182-587649dc-7c2f-4a64-a39a-43e3b1a2d769.png)

Finally, I'm not sure if there is some reasonable way to convert this metric to a test for now, but maybe it could be a part of a process when removing legacy code? Or whenever it makes sense?

What do you think @kcw-grunt?

**Comment by kcw-grunt** [comment]
Thanks for getting in there @Iferencak !
I tend to like the simplest solutions and a reduction of dependencies lets us get more sleep. So using `Option 1` as a Bash  script (Build Phase) seems pretty elegant. 👍🏽

We can also pipe that result into Bitrise somehow (that's icing on cake)

**Comment by Iferencak** [comment]
👍 implemented option 1
