### ISSUE TITLE
🦺[Tech Debt] Mark Unused code script

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#145]
## Goal 
**Describe the work to be done**
 
To further manage our codebase we should add a script that lets us know that we added code that is not being used.
To do this effectively, I recommend adding all the code in a container directory.  This way it wouldn't look at dependencies (which we wouldn't want to touch)

## Reference

```
#Unused
file="${SRCROOT}/BuildTools/unused.rb"
if [ -f "$file" ]
then
echo "$file found."
ruby ${SRCROOT}/BuildTools/unused.rb xcode
else
echo "unused.rb doesn't exist"
fi
```
## Definition of Done
- [x] Compiles and sets warnings when code classes and/or methods are unused
- [ ] Bonus Points: Global switch on / off for developers

**Comment by Iferencak** [comment]
I added the unused ruby script. There were a couple of false-positives so I added the `customFilterNames` array in the script. Usually the delegate methods get flagged so I added the ones I could find in the current codebase to the filter. If there are new false positives, they can just be added to the array. Also, removed names with `"_Previews"` from triggering.

I agree that the file structure in the project should be a bit more structured, but this was not necessary for this task as the script automatically ignores dependencies.

As for the global switch, I couldn't find a neat way to achieve this, @kcw-grunt did you have some specific way how to do this?
