### ISSUE TITLE
[Feature] Add Unstoppable Domains to the Send View

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#154]
## Feature
Let users resolve LTC addresses with HR strings e.g. ;

| UD Domain Name | LTC Address|
|------------------ |--------------|
|`ihatefiat.crypo` |`LStezbCm4YHZut45C4GJrbhHq2H9oz2Q4U`|

**Comment by mosadialiou** [comment]
Closed because the feature is already added
