### ISSUE TITLE
Txn Details Unclickable

### ISSUE THREAD

**Issue by ecurrencyhodler** [litecoin-foundation/loafwallet-ios#171]
Txn details are unclickable. I want to see that txn on the block explorer but I can’t do it without typing the address out now or the txid.

![image0](https://user-images.githubusercontent.com/32662508/102017666-23dd8c80-3d1d-11eb-8461-5be491c7947d.png)

**Comment by kcw-grunt** [comment]
Thanks @ecurrencyhodler
