### ISSUE TITLE
[Bugfix] Txn Details Disappear 

### ISSUE THREAD

**Issue by ecurrencyhodler** [litecoin-foundation/loafwallet-ios#172]
The txn details disappear in the History tab if I click on another button and go back to the history tab. It only reappears after I minimize and expand the details again.
![Screen Shot 2020-12-13 at 8 30 39 AM](https://user-images.githubusercontent.com/32662508/102017723-7dde5200-3d1d-11eb-80be-3aa47eee14f4.png)

**Comment by kcw-grunt** [comment]
Thanks @ecurrencyhodler

**Comment by kcw-grunt** [comment]
Note: This bug is a more complex than it may seem because it is embedded in 2 UIKit technologies (Storyboards, Xibs) and the solution will be SwiftUI solution as the Litewallet UI is migrating accordingly.

**Comment by kcw-grunt** [comment]
Duplicate: https://github.com/litecoin-foundation/loafwallet-ios/issues/98
