### ISSUE TITLE
🦟[Bug Report] v3.10.2 (1597): Litewallet: thunk for @escaping @callee_guaranteed () -> () + 28

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#186]
This is a persistent crash across many versions.  It is not clear what the cause is.

**Describe the bug**

App crashed at runtime (sorry)
 
**Observed Environment**
 - OS version [e.g. _iOS 13.0_]: iOS 13 and higher
 - Litewallet Version [e.g. _v3.4.0_]: Litewallet v3.0.0 and higher
 - Device model:[e.g. _iPhone 11_]: All

**Additional context or information**

Firebase Crashlytics [Bug Report](https://console.firebase.google.com/project/litewallet-beta/crashlytics/app/ios:com.litecoin.loafwallet/issues/2680b07946fb98c0eabb7ad6ee81df84?time=last-seven-days&sessionEventKey=b5d2fb9723674031919b2c7f10739d01_1767700128251618644)

Xcode > Organizer > Crashes > Search for the issue title

**Comment by Iferencak** [comment]
Let me just start by saying that this is really a obscure crash.

After some investigation of the crash stack, it looks like the crash is happening in the `BuyTableViewController.swift`.

Firebase points the crash to line 31, and at frist that was weird, as that is the part of the code that should get triggered after the the user taps on a Moonpay button. 

After more investigation from the apple crash logs i could see that a user reported this crash and set a note that he just "Tried to open the app".

At first, that was strange, but than I saw this on line 31: `let timestamp = Int(appInstallDate.timeIntervalSince1970)`.
`appInstallDate` is computed when the app starts and BuyTableViewController initializes. 

There was a force try `try!` in there that I suspect it was failing as it was trying to get the creation date of a non-existing document. 

I think this was our culprit and the crash should be fixed now.

**Comment by kcw-grunt** [comment]
Merged  https://github.com/litecoin-foundation/litewallet-ios/pull/188
