### ISSUE TITLE
🥳[Feature] Litecoin Card 2FA

### ISSUE THREAD

**Issue by Patrick-t-mcdermott** [litecoin-foundation/loafwallet-ios#193]
This is when you are trying to login to the Litecoin Card. 

When entering 2FA to access the Litecoin card on Litewallet, I submit a number and the keyboard reverts back to letters. I have to change it to numbers for every single digit I enter. 

You could copy/paste but I'm not sure if all of our users are going to be able to do that.

**Comment by kcw-grunt** [comment]
thanks @Patrick-t-mcdermott

**Comment by kcw-grunt** [comment]
More info here: https://github.com/litecoin-foundation/litewallet-team/issues/31
cc: @Patrick-t-mcdermott  @Crypto-Keeper-miners

**Comment by kcw-grunt** [comment]
Will not do Ternio/Unbanked is out of business.
