### ISSUE TITLE
Txn dissapears from history after going into the paper wallet option

### ISSUE THREAD

**Issue by jeff169** [litecoin-foundation/loafwallet-ios#197]
I received LTC from someone and it showed up in my history. About 6 hours later, I then went through the Paper Wallet process, including the verification.  When I completed that, the receipt had disappeared from the history.  Only way to get it back was to sync with the blockchain.  This was in 3.1.1 (3)

Transaction: https://blockchair.com/litecoin/address/LgXYwz7iLaSJsFP6pAM7zMMQpXxZhLjQGh

Wallet address
![IMG_1194](https://user-images.githubusercontent.com/77628627/104931247-25c9e980-5974-11eb-88fa-91f579810be5.PNG)

Missing from history
![IMG_1195](https://user-images.githubusercontent.com/77628627/104931264-2c586100-5974-11eb-8dcb-c853cf73f440.PNG)

**Comment by kcw-grunt** [comment]
Thanks @jeff169 .  This will be labeled and looked at.
