### ISSUE TITLE
Litewallet Feature: Refactor the Login View

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#206]
**Value of feature**
5 points

|**Feature Name**|**Value(Ł)**|
|----------------|------------|
|Refactor Login View |2Ł| 

**Is your feature request related to a problem? Please describe.**
The current app will not have a recent Litecoin price anywhere.  Currently it is hidden. 
Also, users like the idea of sharing a QR code

**Describe the solution you'd like**
Add a recent Litecoin price in the login view and a QR button in the keypad (pinpad) in the login so users can easily show an address

**Describe alternatives you've considered**
Do nothing
 
**Proposed Login Views**
Current | V1 | V2|??
-----|------|----|----
![Simulator Screen Shot - iPhone 12 Pro-boring-proud - 2021-01-24 at 15 55 46](https://user-images.githubusercontent.com/2899463/105635772-a9944200-5e5c-11eb-8074-765954b189c7.png)|![v1login](https://user-images.githubusercontent.com/2899463/105635740-7487ef80-5e5c-11eb-8f29-3ecf788bb77f.png)|![v2Login](https://user-images.githubusercontent.com/2899463/105635737-718cff00-5e5c-11eb-8ba5-d90653149d1c.png)|???

**Comment by kcw-grunt** [comment]
@mosadialiou its important that we refactor for both platforms (Android and iOS)

**Comment by mosadialiou** [comment]
> @mosadialiou its important that we refactor for both platforms (Android and iOS) so that the layout is the same.

I don't like the idea to add the recent LTC price on this view.

**Comment by kcw-grunt** [comment]
@mosadialiou What about the other elements?  Then login view send button (in Android) is a security risk because someone can send LTC without having logging in and it shows their balance....so that needs to be removed (why it was removed from iOS) 
But the show QR is helpful. What are your thoughts on that?

**Comment by mosadialiou** [comment]
@kcw-grunt I don't follow this:

> Then login view send button (in Android) is a security risk because someone can send LTC without having logging in and it shows their balance....so that needs to be removed (why it was removed from iOS)

Here is the login view on Android (what is bad here?)
![Screenshot_1611538525](https://user-images.githubusercontent.com/10891720/105651193-6c5c9e00-5eb6-11eb-9e4f-718561705b1b.png)

**Comment by kcw-grunt** [comment]
Thanks @mosadialiou .  

![Screenshot_1614557050](https://user-images.githubusercontent.com/10891720/109580446-eb1ea980-7afa-11eb-85b1-4b4086134b1b.png)

This one of the options but we never agreed on the final design. _Note it shows v1, v2 , ???_

We should discuss a little on the final location of the QR Code and more imagery to show users what it does.

**Comment by mosadialiou** [comment]
OK sound good!

**Comment by kcw-grunt** [comment]
cc: @antematijaca
I'm on the fence on this. I wondered what you thought? 
We need to have a button to open a QR code for users to show to payers, but I'm not sure where to put it.  Or, how big etc.

**Comment by antematijaca** [comment]
I would go with V1 over V2 for placement. V2 has the QR code icon located within the keypad and it's not logical. I would expect this to be an override function like face ID, or QR code scanner. Not something unrelated to PIN number.

Maybe even place it to the right side of the logo to avoid any confusion that this is a logo or a menu. I think that size like this could work.

Some text below could also come in handy. Like "Show address" or "Share address"


One more thing - current LTC price could maybe show like "1 LTC = $218.74" because some people could see it as their current balance.

**Comment by kcw-grunt** [comment]
@antematijaca I think you are right.  We are having a big problem with the balance in the Android in that the devices are of various resolutions and sizes and different screen sizes and users can change the fiat which causes alot of issues with space.

Do you think you can mock a better option?

**Comment by antematijaca** [comment]
@kcw-grunt sure, I'll give it a try tomorrow and paste a couple of ideas.

**Comment by antematijaca** [comment]
I've managed to sketch some ideas, feel free to comment!

There are some changes to keypad are and if it doesn't make sense, just ignore it. I removed the text below numbers and also added "Forgot your seed phrase..." below. I've seen that in current app so wasn't sure if this is going to be included in an update.

[login_v1.png](https://images.zenhubusercontent.com/604e0e8871af1df6ca8e79ed/819a9b8a-d44d-40b6-a7b1-627698a9d0ad)!

[login_v2.png](https://images.zenhubusercontent.com/604e0e8871af1df6ca8e79ed/22a7c71f-02e9-4723-bb40-04e6d4863538)!

[login_v3.png](https://images.zenhubusercontent.com/604e0e8871af1df6ca8e79ed/4bda3ceb-5282-4eea-8991-50382b4ca085)

**Comment by kcw-grunt** [comment]
Dang @antematijaca v1 is it!!

#### Price Changes
---
Spending weeks working in the help center it is a sad reality that the daily price really confuses people. Some people actually think that when the download Litewallet, they get free Litecoin (seeing the price)....**this is not a joke** 

The other problem is the Android screen sizes mean the daily price is a big problem in the header.  Many fiats need the extra space placing this in the login fixes the issue by removing the price in the header.

#### Forgot Password
---
I like this too because it clears the space between the PIN

#### Next steps
Adding to the next release

**Comment by kcw-grunt** [comment]
Closing with the new layout.

Android: https://github.com/litecoin-foundation/loafwallet-android/issues/242
iOS: https://github.com/litecoin-foundation/loafwallet-ios/issues/248
