### ISSUE TITLE
_Originally posted by @JFrankfurt in https://github.com/Uniswap/token-lists/pull/97_

### ISSUE THREAD

**Issue by Majidbaba** [litecoin-foundation/loafwallet-ios#218]
_Originally posted by @JFrankfurt in https://github.com/Uniswap/token-lists/pull/97_

_Originally posted by @Majidbaba in https://github.com/tronprotocol/java-tron/issues/5637_

_Originally posted by @Majidbaba in https://github.com/tronprotocol/java-tron/issues/5638_

_Originally posted by @Majidbaba in https://github.com/TelegramMessenger/Telegram-iOS/issues/1309_

**Comment by kcw-grunt** [comment]
Please stop spamming @Majidbaba
