### ISSUE TITLE
Required repo is missing: LitewalletPartnerAPI.git

### ISSUE THREAD

**Issue by j4hangir** [litecoin-foundation/loafwallet-ios#223]
I can't compile the wallet, as the needed repo is not available: https://github.com/litecoin-foundation/LitewalletPartnerAPI.git

**Comment by kcw-grunt** [comment]
@j4hangir This is not a bug but a feature. Obviously we need to protect our partners APIs. You can remove references to the private repo to get the code to compile.
(Not a bug)
