### ISSUE TITLE
Wipe wallet causes crash

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#31]
If the user has a wallet and wants to import a new one they must fill in the seed again to delete the datastore.

When they are successful entering the seed and alertview shows that asks the user to  "Wipe Wallet?"

When done the app crashes to a black screen

**Comment by losh11** [comment]
This has been fixed in the lates releases AFAIK.

**Comment by losh11** [comment]
Closing due to duplicate issue (#41)

**Comment by BigslimVdub** [comment]
It doesn’t crash to black screen now, it seems to lock up at the “wiping” screen and does not ask for seed or passcode to wipe wallet. v2.3.5
