### ISSUE TITLE
Disable ignoring paper-key during initial launch

### ISSUE THREAD

**Issue by losh11** [litecoin-foundation/loafwallet-ios#36]
[Current wallet creation flow.](https://youtu.be/kV1Ao9cnsoY)

Notice that the user is able to dismiss the paper-key menu by tapping the X button.
This presents two issues:
1) users complain that they've never written down their paper-key & unable to access wallet
2) users may misread and write down incorrect words due to confirmation only requiring 2/12 words

Solutions
1) Modify paper-key menu to disable dismiss button. Remove dismiss button from all `Paper Key` menus. Shown below.

![First paper-key menu](https://i.redditmedia.com/BC4-d-q0NKYLp4V8Xx7mSXiT5a1JVDVz0XE4mP6Z2hg.png?s=958db5a53d2a1aa696c63b2b80d51293)
![Second and last](https://i.redditmedia.com/jiqxdR0g_5jkbPIMCly1zxIaV3QoCU0KhlL00eT8Tig.png?s=2ec11fd71af5e5521ec6ce4b3b7a47a5)

2) Modify `Confirm Paper Key` menu (shown below) to require all 12 words in numerical order. At the very bottom add a `Confirm Paper Key` menu which is disabled until all words are entered correctly.

![third screenshot thing](https://i.redditmedia.com/GgY7ieXcZD1yZyMMCDyZVsiZsu_lBtfzHJlgMSyZwCQ.png?s=10067f74b27c3a013edb8dbd19c5b1c7)

---------------------------------------

**Precautions:** Force-quitting the app may allow user to bypass `Confirm Paper Key`. Make sure to lock paper-key menu until user has confirmed their paper-key.

**Comment by kcw-grunt** [comment]
On it.

**Comment by losh11** [comment]
Closing due to implementation available.
