### ISSUE TITLE
Bug: Entering 6 digit pin

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#4]
From Alan:

```just wanted to mention that on a few recent transactions where I have sent Litecoin out from Loafwallet, I get stuck when entering in my 6 digit pin. It doesn’t always accept the last digit and wants to lock up and gives an error message. I eventually get it to work but often takes a few attempts. Just wanted to pass this on. Thx. ```

Will add notes related to the code.

**Comment by losh11** [comment]
Is he running LoafWallet 2.0.3? Some users who aren't running the latest build will have this last pin number slow down, and get a `tx timeout` error. I've fixed the pin from getting 'stuck' and also increase `tx timeout` to 30 seconds.

**Comment by kcw-grunt** [comment]
I dunno but we should add Crashlytics to see who is running what...it will tell us what the biggest issues are.

**Comment by kcw-grunt** [comment]
I just experienced this same bug. 

My recommendation is to add a activity indicator.

**Comment by kcw-grunt** [comment]
Found a fix in ApplicationController.performBackgroundFetch() by adding a concurrentQueue extension to make sure peerDisconnect() happens before group.leave() ...Will add in dev build for testing
