### ISSUE TITLE
Payment transfers are slow when adding PIN confirmation is required

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#48]
Litecoin usage is more accessible when payments and transfers are quick and easy. Asking users for a PIN to confirm a cup off coffee is counterproductive.  The proposal is set the biometrics ID (TouchID FaceID) as a default for small amounts.

**Comment by losh11** [comment]
Agreed. Would you be able to implement this?

**Comment by kcw-grunt** [comment]
yep...working on it now..I'll get a Dev build out soon (< days)

**Comment by kcw-grunt** [comment]
Fixed in vpre v.2.3.4 closing
