### ISSUE TITLE
Bugfix: Reset PIN for those who didnt remember but have no LTC in LW(5)

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#59]

**Comment by losh11** [comment]
Implemented in latest release of LoafWallet.

**Comment by BigslimVdub** [comment]
I have this issue with the latest 2.3.5 ip XS where I restore from backup to new phone and LoafWallet does not accept the same pin as old phone. I attempt to wipe and wait 2 hours and it still says “wiping”. Uninstall app and reinstall and it still will not accept pin. Try to wipe again and it just hangs on wiping old wallet. What can I do? Balance is 0 verified on old phone.

**Comment by kcw-grunt** [comment]
Hi George,

Which version are you currently running?
