### ISSUE TITLE
OpenCAP Alias Support

### ISSUE THREAD

**Issue by nuvi-wagner** [litecoin-foundation/loafwallet-ios#60]
The OpenCAP alias protocol allows wallets to easily offer an aliasing feature. This feature lets users send and receive crypto using universal aliases. For instance: "donate$litecoin.org". Getting Litecoin moving on OpenCAP would be huge. Once, a wallet has begun work we add the coin (Litecoin) to the list of supported coin types: https://github.com/opencap/protocol/tree/master/AddressTypes

I would be more than happy to help with any kind of integration. The OpenCAP protocol repo is here:
https://github.com/opencap/protocol

A free to use OpenCAP server is here: https://ogdolo.com

**Comment by kcw-grunt** [comment]
@nuvi-wagner Added this to the project plan for consideration.  Thanks.
