### ISSUE TITLE
zero balance

### ISSUE THREAD

**Issue by houkins** [litecoin-foundation/loafwallet-ios#61]
Hello!
After update to 2.0.5 version I have zero balance and no history of operations. Currently, I have 2.0.5 version. I have checked my connection to a node, app says it is connected and I also I've made Blockchain Sync. Still no result, 0 balance.
I was writing about that issue [here](https://github.com/litecoin-foundation/loafwallet-ios-deprecated/issues/49) but had no response/help.
What should I do? Wait for another update? Or how can I get my money back?

**Comment by losh11** [comment]
Please contact LoafWallet support at contact@loafwallet.org

**Comment by houkins** [comment]
I contacted LoafWallet support at contact@loafwallet.org 11 April 2018 - no respond (email-khart.av@yandex.ru). Second attempt - 1 September 2019. Also no respond. Any other ideas?
