### ISSUE TITLE
Transaction  successfully accepted in the  LTC blockchain but the LW dat file was corrupted

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#63]
Steps to reproduce:

1. Prepare to receive an amount to Loafwallet.
2. Observe the amount is received 100% in the Transactions View 
3. Get into a low bandwidth scenario e.g. "Airplane Mode" for > 8 hrs
4. Open to a full bandwidth mode.
5. Observe transaction is missing from the  Transactions View  yet confirm the amount remains in the blockchain

**Comment by losh11** [comment]
Users should `resync the blockchain` if this occurs - this is what we've been recommending in Support. Otherwise requires complex changes to the loafwallet-core library.

**Comment by kcw-grunt** [comment]
Closing as this was user error.
