### ISSUE TITLE
Wallet crashes when receiving coins from mining

### ISSUE THREAD

**Issue by ikolubr** [litecoin-foundation/loafwallet-ios#73]
App crashes when receiving coins generated from mining. Not when receiving coins from pools that mine to their address and then transfer to your address, but when mining directly, like p2pool or solo mining.

When a block is found and coins credited to the loafwallet address, the app crashes and keeps looping. Have to delete app and download it again to work. Very frustating.

**Comment by sumcoinlabs** [comment]
Dont mine to Loaf Wallet, Mine to your core Wallet.    Send the coin from Loaf out to your core wallet and resync.    SPV isnt always able to handle mining activity.     We experienced this with Slice Wallet on Sumcoin.

**Comment by kcw-grunt** [comment]
@ikolubr  Agree with @sumcoinlabs .  Realize Loafwallet is an SPV Wallet that maintains a fraction of the transactions onto your mobile.  A full-node will be a better way of having a full, fresh copy of the blockchain....  You could run a legacy PC running onto your network setup to run Litecoin-QT.

Note also the network quality will affect the mobile for any app....for a peer-to-peer network the bar is far higher.
