### ISSUE TITLE
zero balance

### ISSUE THREAD

**Issue by houkins** [litecoin-foundation/loafwallet-ios#75]
Hello!
After update to 2.0.5 version I have zero balance and no history of operations. Currently, I have 2.3.5 version. I have checked my connection to a node, app says it is connected and I also I've made Blockchain Sync. Still no result, 0 balance. 
I was writing about that problem [here](https://github.com/litecoin-foundation/loafwallet-ios/issues/61), but the issue was closed and I still have zero balance. 
I contacted LoafWallet support at contact@loafwallet.org 11 April 2018 - no respond (email-khart.av@yandex.ru). Second attempt - 1 September 2019. Also no respond. 
What should I do? How can I get my money back?

**Comment by kcw-grunt** [comment]
The worst case scenario is to restore to a different wallet using your 12 word phrase
