### ISSUE TITLE
Kindly solve the Swedish localisation

### ISSUE THREAD

**Issue by stenerikbjorling** [litecoin-foundation/loafwallet-ios#79]
The screens for settings etc. do not contain any Swedish texts.

**Comment by kcw-grunt** [comment]
thanks @stenerikbjorling   can you provide 1 - 2 screenshots for reference?

**Comment by stenerikbjorling** [comment]
Hi,

Here you go…



Take care, all the best…

Stene

_______

**Comment by kcw-grunt** [comment]
This seems to be there and localized (v2.4.1):

Am I missing something?

![Screen Shot 2019-11-02 at 2 00 05 PM](https://user-images.githubusercontent.com/2899463/68077017-b4efdf00-fd79-11e9-92c3-8f856972889c.png)

**Comment by stenerikbjorling** [comment]
Hi, solven with the latent uppdatera.

Thanks for good work!

Stene


Skickat från min iPad

**Comment by kcw-grunt** [comment]
My pleasure!  Please share LiteWallet with your friends!  And feedback is always welcome!
