### ISSUE TITLE
WalletManagerSave:

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#9]
Testflight crash logs show a list of crashes that are probably linked to an old version on the loafwallet-core submodule that was forked from breadwallet.

**Comment by kcw-grunt** [comment]
Need to pull up changes from breadwallet core and run a test regime to monitor

**Comment by kcw-grunt** [comment]
@losh11 will rebase loafwallet-core to current breadwallet-core lib to fix the crashes.

**Comment by losh11** [comment]
Merged
