### ISSUE TITLE
🥳[Feature] Export xpub key

### ISSUE THREAD

**Issue by kcw-grunt** [litecoin-foundation/loafwallet-ios#90]
### Why?
Litepay operators can use the xpub key to sync their copy of Litewallet with their LTCPay server.

### What?
Add a UI flow to allow the user to export the xpubkey.

### Definition of Done
- [ ] Add Tests  that export function and copy and button functions
- [ ] Create a model that creates the xpub key string
- [ ] Add a cell in `Settings > Blockchain > Export Xpub key`
- [ ] Add  a view  showing the xpub key and the supporting information

### Draft of Changes / Workflow
Refer to : https://github.com/litecoin-foundation/Litewallet-Project/issues/20
---
This changes would match the mockup:

![Untitled87](https://user-images.githubusercontent.com/2899463/133927758-fe3bec9f-228f-4418-a8e5-1e4d125c9294.png)

**Comment by wangxinxi** [comment]
Thanks. This looks great! It would be even better if you can make the copy function more obvious by including a copy button beside the xpub key.

**Comment by losh11** [comment]
Unfortunately Litewallet uses hardened xpub keys. This means that without the parent private key, it will not be possible to derive any addresses. LTCPayServer does not accept hardened keys for this reason. Please see this for more info: https://bitcoin.stackexchange.com/questions/107646/how-exactly-can-hardened-keys-work-hd-wallets

Reccomending issue closure.
