### ISSUE TITLE
Serious UI bug for iOS when trying to send

### ISSUE THREAD

**Issue by andzsy** [litecoin-foundation/loafwallet-ios#92]
Hi, you can see in the picture below that the numeric keypad when trying to send LTC from Litewallet only shows the digits 1-8.  You can't key in a 9, 0 or a decimal point at all, nor can you edit the input string (eg can't backspace or select).

This is running under iOS 12.1.1 on a 2nd Gen iPad Air. 

This problem doesn't seem to occur on, say, an iPhone.

![Litewallet](https://user-images.githubusercontent.com/18174885/73516888-dc1b8280-4434-11ea-861a-23aee033cce6.PNG)

**Comment by kcw-grunt** [comment]
Thanks @andzsy this is serious UI issue.  
Unfortunately, this and many views in the app were written without consideration for iPad. 
We may drop support for iPad in the next major release and only support iPhone devices as we consider the other issues and the iPad related issues.

**Comment by losh11** [comment]
This issue is trivial to fix. And should be targeted for the next available release. As a 'critical' issue, removing iPad support would have no difference to the current situation.

**Comment by kcw-grunt** [comment]
Actually the view is using NSLayoutConstraints and is calculated (I reviewed it over 1 year ago) causing a considerable number of dev cycles.

This will be the new form. Smaller screen size but works on iPad.

![IMG_0421](https://user-images.githubusercontent.com/2899463/73520221-f9f6d200-43b7-11ea-910b-70f2b62dd9d3.PNG)

**Comment by kcw-grunt** [comment]
@andzsy if you need to urgently need to access your wallet email litewallet@litecoinfoundation.net and you can be added to the Testflight program where this update is already present fixed.

**Comment by kcw-grunt** [comment]
a Litewallet team member was able to sort this out.

**Comment by kcw-grunt** [comment]
Fixed in https://github.com/litecoin-foundation/loafwallet-ios/pull/101
